name: flutter_timezone_plus
description: A fork of https://pub.dev/packages/flutter_timezone works on windows and linux
version: 1.1.1
homepage: https://github.com/ozayakcan/flutter_timezone_plus

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  js: '>=0.6.3 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.ozayakcan.flutter_timezone_plus
        pluginClass: FlutterTimezonePlusPlugin
      ios:
        pluginClass: FlutterTimezonePlusPlugin
      macos:
        pluginClass: FlutterTimezonePlusPlugin
      web:
        pluginClass: FlutterTimezonePlugin
        fileName: flutter_timezone_plus_web.dart
      linux:
        pluginClass: FlutterTimezonePlusPlugin
      windows:
        pluginClass: FlutterTimezonePlusPluginCApi
